name: Build and Deploy to RC

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test    
    steps:
      - name: Execute command
        run: echo Hello World ${{ vars.Message}}!