name: Build and Deploy to Test

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v4
      
      - name: Execute command
        run: echo Hello World ${{ vars.Message }}!

